/** App-owned browser companion for standard injected EIP-1193/EIP-6963 wallets. */
export function browserWalletPage(nonce: string) {
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PolyAgent · 钱包签名</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#f3f7f8;color:#183d48;font:15px/1.65 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif}main{max-width:780px;margin:48px auto;padding:0 24px}h1{font-size:28px;margin-bottom:8px}h2{font-size:18px}p{color:#526b73}section{background:white;border:1px solid #dce6e8;border-radius:12px;padding:24px;margin:22px 0}button,select{font:inherit;border:1px solid #cbd9de;border-radius:7px;padding:9px 14px;background:white;color:#183d48;margin:4px 8px 4px 0;max-width:100%}button{cursor:pointer}button.primary{background:#087f82;color:white;border-color:#087f82}button:disabled{opacity:.48;cursor:not-allowed}button:focus-visible,select:focus-visible{outline:3px solid #13878b;outline-offset:3px}code{word-break:break-all}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:300px;overflow:auto;background:#f3f7f8;padding:12px;font-size:12px}#notice{min-height:28px}#notice.error{color:#963d2d}label{display:block;font-weight:600}.actions{display:flex;flex-wrap:wrap}[hidden]{display:none!important}</style>
<main><h1>连接钱包，确认每次签名</h1><p>PolyAgent 的本机钱包窗口。私钥保留在你的钱包里；交易所认证、订单签名和链上操作都由你在钱包中确认。</p>
<section><h2>Polymarket 账户</h2><code id="account">正在验证本机连接…</code><p>这是持有资金的账户钱包，可能与下面连接的签名地址不同。</p><label for="wallets">选择浏览器钱包</label><select id="wallets" disabled><option>正在查找钱包</option></select><div class="actions"><button id="connect" class="primary" disabled>连接钱包</button><button id="disconnect" disabled>断开连接</button></div><p id="identity">连接后请保持这个窗口打开。关闭或切换账户、网络会停止本次签名会话。</p></section>
<section id="signing" hidden><h2 id="request-title">待确认签名</h2><p id="expires"></p><details><summary>查看完整请求</summary><pre id="payload"></pre></details><div class="actions"><button id="sign" class="primary">在钱包中确认</button><button id="reject">拒绝本次请求</button></div></section><p id="notice" role="status" aria-live="polite"></p></main>
<script nonce="${nonce}">
(()=>{
 const byId=id=>document.getElementById(id), notice=byId('notice');
 const providers=[]; let provider=null, address='', token='', connected=false, pending=null, signing=false, active=true, polling=false;
 const say=(text,error=false)=>{notice.textContent=text;notice.className=error?'error':'';};
 const api=async(path,body={},credential=token)=>{const response=await fetch('/wallet/'+path,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+credential},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'本机钱包连接失败');return data;};
 const renderProviders=()=>{const select=byId('wallets');select.replaceChildren();providers.forEach((item,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=item.name;select.append(option);});if(!providers.length){const option=document.createElement('option');option.textContent='未发现浏览器钱包';select.append(option);}select.disabled=connected||!token||!providers.length;byId('connect').disabled=connected||!token||!providers.length;};
 window.addEventListener('eip6963:announceProvider',event=>{const item=event.detail;if(!item?.provider?.request||providers.some(x=>x.provider===item.provider))return;providers.push({provider:item.provider,name:String(item.info?.name||'浏览器钱包').slice(0,80)});renderProviders();});
 window.dispatchEvent(new Event('eip6963:requestProvider'));
 setTimeout(()=>{if(!providers.length&&window.ethereum?.request){providers.push({provider:window.ethereum,name:'已安装的钱包'});renderProviders();}},500);
 const end=async(message)=>{connected=false;active=false;byId('signing').hidden=true;byId('connect').disabled=true;byId('disconnect').disabled=true;byId('wallets').disabled=true;try{await api('disconnect');}catch{}token='';say(message,true);};
 byId('connect').onclick=async()=>{byId('connect').disabled=true;try{provider=providers[Number(byId('wallets').value)].provider;const accounts=await provider.request({method:'eth_requestAccounts'});if(!accounts?.[0])throw new Error('钱包未提供账户');if(await provider.request({method:'eth_chainId'})!=='0x89')await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x89'}]});const chainId=await provider.request({method:'eth_chainId'});const current=await provider.request({method:'eth_accounts'});address=current[0];await api('connect',{address,chainId});connected=true;renderProviders();byId('disconnect').disabled=false;byId('identity').textContent='签名地址：'+address+' · Polygon';provider.on?.('accountsChanged',()=>void end('钱包账户已变化，请回到 PolyAgent 重新连接。'));provider.on?.('chainChanged',()=>void end('钱包网络已变化，请回到 PolyAgent 重新连接。'));provider.on?.('disconnect',()=>void end('钱包已断开，请回到 PolyAgent 重新连接。'));say('已连接。回到 PolyAgent 核对账户，再启动所选策略。');}catch(error){say(error.message||'连接未完成',true);byId('connect').disabled=false;}};
 byId('disconnect').onclick=()=>void end('已断开。未提交的签名已取消；已经提交的订单与交易仍需核对。');
 const poll=async()=>{if(!active||!token||polling)return;polling=true;try{const result=await api('poll');pending=result.request;byId('signing').hidden=!pending;byId('sign').disabled=signing;byId('reject').disabled=signing;if(pending){byId('request-title').textContent=pending.method==='eth_sendTransaction'?'待确认链上交易':'待确认钱包签名';byId('payload').textContent=JSON.stringify({method:pending.method,params:pending.params},null,2);byId('expires').textContent='请在 '+Math.max(0,Math.ceil((pending.expiresAt-Date.now())/1000))+' 秒内确认；超时不会自动重发。';}}catch(error){active=false;byId('connect').disabled=true;byId('signing').hidden=true;say(error.message,true);}finally{polling=false;}};
 byId('sign').onclick=async()=>{if(!pending||signing||!connected)return;const selected=pending;signing=true;byId('sign').disabled=true;byId('reject').disabled=true;try{const live=await api('poll');if(live.request?.id!==selected.id)throw new Error('请求已过期');const accounts=await provider.request({method:'eth_accounts'});const chain=await provider.request({method:'eth_chainId'});if(accounts[0]?.toLowerCase()!==address.toLowerCase()||chain!=='0x89')throw new Error('账户或网络已变化');const result=await provider.request({method:selected.method,params:selected.params});await api('respond',{id:selected.id,result});say('钱包已返回结果。请回到 PolyAgent 查看实际订单或链上状态。');}catch(error){try{await api('respond',{id:selected.id,rejected:true});}catch{}say(error.message||'钱包未确认本次请求',true);}finally{signing=false;await poll();}};
 byId('reject').onclick=async()=>{if(!pending||signing)return;try{await api('respond',{id:pending.id,rejected:true});say('已拒绝本次请求。');await poll();}catch(error){say(error.message,true);}};
 (async()=>{const link=location.hash.slice(1);history.replaceState(null,'','/wallet');try{const result=await api('claim',{},link);token=result.token;byId('account').textContent=result.walletAddress||'执行器尚未配置账户钱包';renderProviders();say(providers.length?'选择钱包后连接。':'请在安装了 MetaMask、Rabby 等钱包扩展的浏览器中打开此页面。');await poll();setInterval(poll,1000);}catch(error){active=false;say(error.message,true);}})();
})();
</script></html>`;
}
